### ISSUE TITLE
Decision needed: `Pay.B(7) == Pay.B(7)` is false on x86_64 — what does equality mean for a payload variant?

### ISSUE THREAD

**Issue by nizovtsevnv** [alatyr-programming-language/compiler#469]
## Question first, then the measurement

Is structural equality on a **payload-carrying** enum variant meant to compare payloads, compare only the
discriminant, or be refused? The pinned specification revision (`b4e7979`) needs to answer this before the
observation below can be called a defect, and I am filing it as a decision rather than asserting one.

## Measured

Found while working #449 (PR #468), on x86_64 — the reference backend:

```
Pay := enum { A(u64), B(u64, u64) }
```

- `Pay.B(7) == Pay.B(7)` is **false**.
- `e == Pay.B(7)`, with `e` bound to `Pay.B(7)`, answers **91** (the fixture's "no arm matched" code).

The comparison compiles cleanly and produces no diagnostic. If payload comparison is intended, this is a
silent wrong value on the reference backend. If only the discriminant is intended to participate, then
two `Pay.B` values with different payloads would compare equal, which is a different surprise and should
be written down. If the form is meant to be refused, it currently is not.

By contrast a discriminant-only enum (`Tag := enum { Red, Green, Blue }`) compares correctly on x86_64,
which is why this went unnoticed: the common case works.

## Why the answer matters beyond x86_64

The wasm backend currently traps on every enum comparison, and PR #468 deliberately made a struct's enum
**field** trap too rather than answer, for exactly this reason: comparing discriminants alone would
silently miscompile a payload enum. That choice is sound under any of the three readings above, but the
*correct* wasm implementation depends on which reading is right — and so does whether x86_64 is currently
wrong.

`base::derive::eq` is what x86_64 uses; wasm has no structural eq/lt derive at all.

## What is needed

1. The specification's position, quoted, on equality for a variant carrying a payload. If the spec is
   silent, this is a decision to record before any code changes — `AGENTS.md`: *"Decide language questions
   in the specification before changing `src/`. If the specification is silent, stop and get the decision
   recorded; do not infer semantics from current behavior."*
2. Once recorded: either fix `base::derive::eq` (with a fixture that distinguishes *equal payloads*,
   *same variant with different payloads*, and *different variants* by distinct exit codes), or make the
   form a located reject, or document the discriminant-only semantics and add a fixture pinning it.

Whichever way it goes, the current state — compiles cleanly, answers "not equal" for two identical values
— is not one of the three.

## Related

- **#449** / PR #468 — where this was measured; that PR's fail-loud choice for wasm is unaffected by the
  answer.
- **#464** — the class of silently-successful paths; if this turns out to be a defect it is another member.

## Scope

`area:lower`, needs a specification decision before implementation. Not claimed as `wrong-value` until
the intended semantics is recorded.

**Comment by nizovtsevnv** [comment]
> *This was generated by AI during triage.*

## Research report

**Established:**

- **The specification answers the question, and it answers reading 1: equality on a payload-carrying
  variant compares the payload.** Readings 2 (discriminant-only) and 3 (refuse) are both excluded by
  normative text at the pin. No owner decision is needed.
- The current x86_64 behaviour is therefore a **silent wrong value**, but the defect is *not* "enum
  payload equality"; that path is already correct. The defect is one operand-classification gate, and it
  hits **structs, `Option`, and enums alike**, in **both** directions (wrongly equal and wrongly unequal).
- The issue's headline example does not reproduce verbatim at `fd64f1d` (see the correction below); its
  second measurement (`e == Pay.B(...)` → 91) reproduces exactly.
- PR #468's fail-loud choice for wasm is **safe under all three readings** — with one named residual.

---

### Evidence — the pinned specification (`b4e7979`)

**Enum equality is defined, and it compares payloads.** `spec/160-appendix-stdlib.md:118-132`:

> #### 2.6 `Eq` / `Ord` / `Hash` — equality, ordering, hashing (derived structurally)
>
> The comparison operator-functions (`==` `!=` `<` `<=` `>` `>=`, eager → `bool`; Control
> Flow §8 / OP-2) and `HashMap` keys (§6) rest on operations the prelude **derives
> structurally** over `typeinfo(T)` (Comptime §5.3) […] The derive walks each kind by its `typeinfo`
> shape: a **struct**'s fields via `a.(f)` (Comptime §5.4), an **array**'s elements by index,
> and an **enum**'s variants via the comptime variant pattern `T.(v)` in a `comptime
> for`-unrolled `match` (Comptime §5.5 / CT-9) — a scalar leaf compares directly. […]
>
> - **`Eq`** — `eq(in a : T, in b : T) -> bool` (backs `==` / `!=`); default = componentwise
>   field equality.

**And Comptime §5.5 spells the enum case out, normatively and by example.**
`spec/30-comptime.md:337-343`:

> - **The comptime variant pattern `T.(v)`** — in pattern position, resolved at comptime to the concrete variant pattern
>   `T.<v.name>` […] `T.(v)(p)` binds the matched variant's **whole payload** as
>   one value `p` — a **tuple** when the variant has several components (§5.1: `Variant.payload` is that whole payload) —
>   so a derive compares it by **recursing with the operator** (`p_a == p_b`).

`spec/30-comptime.md:347-357` — the specification's own `eq` body:

> ```
> # (inside eq, comptime-selected when typeinfo(T) is Enum)
> match a {
>   comptime for v in typeinfo(T).variants {     # unrolled once per variant
>     T.(v)(pa) => match b {                      # T.(v) ≡ T.<v.name>, monomorphized
>       T.(v)(pb) => return pa == pb              # same variant: compare payloads (recurse)
>       _         => return false                 # different variant ⇒ not equal
>     }
>   }
> }
> ```

That closes all three readings:

| reading | verdict at the pin |
|---|---|
| 1 — compares payloads | **this is the rule**: "same variant: compare payloads (recurse)"; "different variant ⇒ not equal" |
| 2 — discriminant only | **excluded.** `Pay.B(7,7) == Pay.B(9,9)` must be `false`. `design/decisions/comptime.md:192-194` also rejects *"Raw-byte enum compare — padding and pointer/aggregate payloads make it non-structural"* |
| 3 — refuse the form | **excluded.** §2.6:122-123 — a type "provides them **by default**"; `spec/160-appendix-stdlib.md:710` makes it conformance: a conforming implementation MUST "**derive `eq`/`lt`/`hash` structurally** over `typeinfo`" |

Two further normative rows: `spec/30-comptime.md:687-694` (conformance) requires the comptime variant
pattern as "the struct and enum halves of a structural derive", and
`spec/160-appendix-stdlib.md:404` requires `Variant.payload` to be the **tuple** of all component types
for a multi-component variant — so a two-component payload is compared as a whole tuple, not by its
first component.

**Aggregate equality generally (question 2) — also defined, and not asymmetric.** §2.6:131-132 gives one
rule for every kind ("default = componentwise field equality"), and `spec/30-comptime.md:320-327` gives
the struct body:

> ```
> eq := fn(T : type, in a : T, in b : T) -> bool {
>   comptime for f in typeinfo(T).fields {       # unrolled once per field
>     if a.(f) != b.(f) { return false }         # a.(f) ≡ a.<f.name>, monomorphized
>   }
>   return true
> }
> ```

Arrays are covered by the same sentence ("an **array**'s elements by index"). A **tuple** is a product
in the same section as `struct` (`spec/20-types.md:413,419` — "#### 6.1 Product — `struct` and tuple";
"A **tuple** is an anonymous positional product […] with **structural** identity"), and `TypeInfo`
(`spec/160-appendix-stdlib.md:391-401`) has no separate `Tuple` kind, so a tuple takes the product arm.
So there is **no gap** between struct equality and enum equality in the specification — both are the one
componentwise rule, stated once in §2.6 and given a body per kind in Comptime §5.4/§5.5.

Two things the pin genuinely leaves implicit, neither of which affects this issue: the `Field.name` a
tuple's positions reify with (the product arm iterates `fields` whatever they are named), and whether a
**view** (`[T]` / `str`) equality walks its elements or its `{ptr,len}` pair — §3.5 and §3.6
(`spec/160-appendix-stdlib.md:300-345`) state no separate rule, so it too falls out of §2.6's one
componentwise sentence. Worth recording in the specification at some point; not a blocker here.

---

### Evidence — the measured mechanism (independent reproduction, `fd64f1d`, own detached worktree)

`lib/base/derive.al:39-46` is **already spec-shaped** — it is a verbatim transcription of Comptime
§5.5's body — and it is not where the defect lives:

```alatyr
return match a {
  comptime for v in typeinfo(T).variants {
    T.(v)(pa) => match b {
      T.(v)(pb) => pa == pb
      _ => false
    }
  }
}
```

The defect is the **routing gate** that decides whether a bare `==` reaches that derive at all.
`src/lower.al:15483`:

```alatyr
if agg_value_var_words(l, cx, a) > 1 and agg_value_var_words(r, cx, a) > 1 {
```

and `agg_value_var_words` (`src/lower.al:1170-1178`) opens with `vn := var_name_span(e); if vn.n == 0
{ return 0 }` — it answers non-zero **only for a `Var`**. An aggregate **constructor expression**
(`P(x = …)`, `E.V(payload)`) is not a `Var`, so the routing declines for it and the operand falls to the
scalar path below. And there, a multi-word aggregate constructor in a scalar value position materializes
as the **constant `$0`** — not word 0, not an address. Read out of the emitted GAS for
`Pay.A(1) == Pay.B(1, 1)`:

```gas
  pushq $0          ## the LEFT enum construction  -> $0
  movq $0, %rbx     ## the RIGHT enum construction -> $0
  popq %rax
  cmpq %rbx, %rax
  sete %al
```

so it answers **equal**, for two *different variants*. Where one side is a `Var`, that side loads its
real word 0 (an enum's tag, a struct's first field) and is compared against `$0`, so the answer is
"equal" iff that word happens to be zero. A **payload-free** variant literal is unaffected — it
materializes its discriminant correctly (`Tag.Red` → `$0`, `Tag.Green` → `$1`) — which is exactly why
the common case looked healthy.

**Measured on x86_64** (each program returns a distinct code; exit read outside any pipeline):

| source | answered | spec-due | |
|---|---|---|---|
| `Pay.B(7,7) == Pay.B(7,7)` | equal | equal | right answer, wrong reason (`$0 == $0`) |
| `Pay.B(7,7) == Pay.B(9,9)` | **equal** | not equal | **wrong** |
| `Pay.A(1) == Pay.B(1,1)` | **equal** | not equal | **wrong** |
| `e == Pay.B(7,7)`, `e := Pay.B(7,7)` | **not equal (91)** | equal | **wrong** — the issue's own measurement |
| `probe(e : Pay) { e == Pay.B(7,7) }` | **not equal (91)** | equal | **wrong** (param operand) |
| `E.A(1) == E.A(2)` (`E := enum { A(u64), B(u64) }`) | **equal** | not equal | **wrong** (1-component too) |
| `e == E.A(2)`, `e := E.A(1)` | **equal** | not equal | **wrong** |
| `Option.Some(1) == Option.Some(2)` | **equal** | not equal | **wrong** |
| `Option.None == Option.Some(5)` | **equal** | not equal | **wrong** |
| `o == Option.Some(1)`, `o := Option.Some(1)` | **not equal (91)** | equal | **wrong** |
| `p == P(x=5,y=7)`, `p := P(x=5,y=7)` | **not equal (91)** | equal | **wrong** — a plain struct |
| `P(x=5,y=7) == P(x=5,y=9)` | **equal** | not equal | **wrong** |
| `p < P(x=5,y=9)`, `p := P(x=5,y=7)` | **not less** | less | **wrong** (`lt`'s fail-loud guard is never reached — the gate declines first) |
| `e == f`, both locals, 2-component payload, equal | equal | equal | correct (routes to the derive) |
| `e == f`, both locals, payloads differ in component 2 | not equal | not equal | correct |
| `Tag.Red == Tag.Green` / `t == Tag.Green` / `h.t == Tag.Green` | correct | correct | payload-free enum unaffected |

So `Option` — the most-used enum in the language — silently answers `Some(1) == Some(2)` **true**, and
`o == Option.Some(1)` **false** for an `o` bound to that very value.

**The gate never measured this class.** `test/agg_eq.al` and `test/enum_eq_payload.al` compare **locals
only**; `scripts/e2e.sh:3813-3816` says so in its own words ("over TWO multi-word by-value struct/enum
values"). No fixture in `test/` bare-compares an aggregate **constructor expression**, so no
`scripts/corpus.manifest` row, no `scripts/needle.baseline` row, no `scripts/idiom.baseline` row and no
`fmt_corpus.sh` ALLOW row records or blesses any of the wrong values above. **There is no oracle-backed
residual masking this issue** — checked row by row for `agg_eq`, `enum_eq_payload` and
`comptime_enum_eq` (all `run`-only, x86_64 42, other backends 133/134 trap).

**Correction to the issue text (context preserved, not rewritten).** At `fd64f1d`,
`Pay.B(7) == Pay.B(7)` answers **true**, not false — both sides are `$0`. The recorded `false` was
presumably measured on a different tree or spelling; the issue's *other* measurement, `e == Pay.B(7)`
→ **91**, reproduces exactly and is the same defect. Separately: `Pay.B(7)` supplies **one** component
to `B(u64, u64)` and builds with no diagnostic, though `spec/20-types.md:983-996` §9.3 gives the enum
variant constructor and §9.4:1000-1004 states there is "**no implicit, language-imposed default or
zero-initialization**". That is a distinct finding (below), not part of this issue.

---

### Question 4 — is #468's fail-loud choice safe under all three readings?

**Yes, under all three**, and the specification's answer (reading 1) does not retroactively make it
wrong:

| reading | is a wasm trap safe? |
|---|---|
| 1 — compares payloads (**the rule**) | Safe. wasm has no structural derive, so it cannot *answer*; a located trap is a refusal, not a wrong value — `AGENTS.md`: *"A trap is acceptable; a wrong value is not. If correctness cannot be completed, leave a located reject."* #468 turned a silent 91/52 into a 134, which is strictly the right direction. Its own PR text records the residual and #449 stays open. |
| 2 — discriminant only | Safe. Still no wrong value. It would merely be *stricter than needed* for a payload-free enum. |
| 3 — refuse the form | Safe, and would be the final state. |

**Its one named residual, which this research adds rather than contradicts.** `wat_is_agg_place` has the
**same `Var`-shaped blind spot** as `src/lower.al`'s gate: a **constructor-expression** operand slips
past it on wasm too, and the emitted WAT compares two freshly-allocated **block addresses**. Measured
under `wasmtime` (`alatyr wat` → `wat2wasm` → `wasmtime`, exit read outside a pipeline):

| source | wasm | x86_64 | spec-due |
|---|---:|---:|---|
| `P(x=5,y=7) == P(x=5,y=7)` | **91** | 10 | equal — wasm **silently wrong** |
| `Tag.Red == Tag.Red` (payload-free!) | **91** | 10 | equal — wasm **silently wrong** |
| `Pay.B(7,7) == Pay.B(7,7)` | **91** | 10 | equal — wasm **silently wrong** |
| `Option.Some(1) == Option.Some(2)` / `o == Option.Some(1)` / `e == Pay.B(7,7)` | 134 trap | wrong value | the existing fail-loud |

The WAT for the first row is an `i64.eq` between two `(block (result i64) … (global.get $__tmp))`
scratch-block addresses, each of which bumps `$__sp` — so two structurally equal literals can never
compare equal there. This is **not** #449 (no struct field is involved) and **not** covered by #468;
it needs its own issue. `aarch64` and `riscv64` are fail-loud on every one of these shapes
(`brk #0 // unsupported expr`, `ebreak`), consistent with `src/aarch64.al:4154` / `src/riscv64.al:3485`.

---

**Conclusion: `spec-answered`.** The semantic question is answered by the pin; no design, security or
authorization decision remains.

### Implementation brief

**Current behaviour.** On x86_64, a bare comparison operator whose operand is an aggregate
**constructor expression** (a struct literal `P(x = …)` or a payload-carrying variant construction
`E.V(…)`) declines the structural routing at `src/lower.al:15483` — `agg_value_var_words`
(`src/lower.al:1170-1178`) answers 0 for anything that is not a `Var` — and that operand then
materializes as the scalar constant `$0`. Wrong values result in both directions, for structs, `Option`
and payload enums (table above). Ordering (`<`/`>`/`<=`/`>=`) is affected identically and does **not**
reach its existing fail-loud guard, because the gate declines before it.

**Desired behaviour** (`spec/160-appendix-stdlib.md:118-132`, `spec/30-comptime.md:320-357`,
`spec/160-appendix-stdlib.md:404,710`): componentwise. For a payload variant, equal iff the **same
variant with equal payloads**, the whole payload (a tuple when multi-component) recursed through the
operator; different variants are not equal. `lt` is lexicographic by declaration order, variant order
first. Per `AGENTS.md`, any shape whose correctness cannot be completed must become a **located reject**
— never a silent wrong value, and never the current `$0`.

**Key interfaces.**
- `src/lower.al:15426-15516` — the bare-comparison routing block; `src/lower.al:15483` is the gate.
- `src/lower.al:1170-1178` `agg_value_var_words` — the `Var`-only classifier.
- `src/lower/mono.al:110-112, 289-306` — the derive-instance pre-pass must register the instance for
  whatever new operand shape is routed, or the program link-fails on `base__derive__eq__<T>`.
- `lib/base/derive.al:39-46` is already correct — **do not change it** to "fix" this.

**Acceptance criteria.**
1. Every row of the x86_64 table above answers the spec-due value, **or** is a located reject with a
   named diagnostic. No row may keep a silent wrong value, and no row may keep the accidental
   `$0 == $0` "right answer, wrong reason" — including the two rows that currently read correct by
   accident (`Pay.B(7,7) == Pay.B(7,7)`, `P(x=5,y=7) == P(x=5,y=7)`).
2. One fixture registered in `scripts/e2e.sh` that **fails on the parent**, distinguishing by **distinct
   exit codes** (all < 126, no alias encoding): *equal payloads*, *same variant with different
   payloads*, *different variants*, *struct literal vs equal local*, *struct literal vs differing
   literal*, and an `Option.Some(x) == Option.Some(y)` pair. `build_reject_has` (not `build_reject`) for
   any shape that becomes a reject, with the needle outside the fixture header.
3. The already-correct paths do not move: `e == f` over two locals (both 1-component and
   multi-component payloads), `test/agg_eq.al`, `test/enum_eq_payload.al`, `test/comptime_enum_eq.al`,
   and every payload-free enum shape (`Tag.Red == Tag.Green`, `t == Tag.Green`, `h.t == Tag.Green`).
4. GAS delta measured with the **input tree held fixed, in both directions**; fixpoint green. The gate's
   own note says `src/`/`lib/` make no bare aggregate comparison, so the change should be
   fixpoint-neutral — measure that, do not assert it.
5. The new fixture's non-x86 columns must not **bless a wrong value**: `aarch64`/`riscv64` are fail-loud
   here, and wasm silently answers three of these shapes wrongly (table above). Do **not** add a
   `run_wat` e2e row that records a wrong wasm answer; let the corpus manifest carry the wasm column and
   reference the wasm issue instead.

**Scope boundary — out of scope for this issue.** Each of the following is a separate finding measured
in the course of this research, and each needs its own issue rather than being folded in here:
- **wasm** silently answers `P(5,7) == P(5,7)`, `Tag.Red == Tag.Red` and `Pay.B(7,7) == Pay.B(7,7)`
  as **not equal** (block-address compare). Distinct from #449 (no struct field) and not covered by
  #468, whose `wat_is_agg_place` guard has the same `Var`-only blind spot.
- An enum variant whose payload is a **struct** cannot be compared at all: `E := enum { A(P), B(u64) }`
  with two locals **link-fails** — `undefined reference to base__derive__eq__P` — i.e. the mono
  worklist does not collect the nested product derive for an enum payload. Loud, so not a wrong value,
  but it means the recursion Comptime §5.5 requires is incomplete one level down.
- `Pay.B(7)` for `B(u64, u64)` builds with no diagnostic (see §9.3/§9.4 above).
- Making wasm *answer* an enum comparison at all (needs a structural derive there) — #449's residual.

**Spec basis.** `spec/160-appendix-stdlib.md:118-136` (§2.6), `spec/160-appendix-stdlib.md:391-404`
(`TypeInfo`/`Variant.payload`), `spec/160-appendix-stdlib.md:703-712` (§8 conformance 1),
`spec/30-comptime.md:302-327` (§5.4), `spec/30-comptime.md:329-361` (§5.5 / CT-9),
`spec/30-comptime.md:687-694` (§11 conformance 7), `spec/20-types.md:413-426` (§6.1),
`spec/20-types.md:432-446` (§6.2), `design/decisions/comptime.md:168-194` (CT-9, incl. the rejected
raw-byte compare). Pinned at spec `b4e7979`.

**Transition:** `needs-info` is removed. The specification answers the semantic question at the pin, the
brief above is complete, no oracle-backed residual masks the class, and no design, security or
authorization decision is outstanding. This report is evidence, not authorization: the implementation
operation must invoke `alatyr-lane` with **#469** and repeat its own preflight and safety review. The
`in-progress` claim made by this research run is released.

**Comment by nizovtsevnv** [comment]
Decision made, implemented by #525, landed in `main` at `71ea8df` (merge `bc17442`).

### The decision, and it did not need me to invent one

I opened this as "decision needed" on the premise that the specification might be silent on what
equality means for a payload-carrying enum. It is not silent. It answers twice, independently:
§2.6 of the stdlib appendix states componentwise equality for aggregates, and the normative `eq` body
in Comptime §5.5 recurses **with the operator**, which fixes the recursion rather than leaving it to
the implementation. So `Pay.B(7) == Pay.B(7)` is `true` by the specification, and x86_64 answering
`false` was a defect, not an open design question.

My framing was wrong in a second way as well: the defect was not in equality at all. It was in operand
routing — an aggregate **constructor** used as an operand was materialised as `$0` because
`agg_value_var_words` opens by asking for a variable name span and returns 0 for anything that is not a
`Var`. Equality then compared two zeros correctly.

Per **#507**'s standing caveat, the zero-CHANGED claim was corroborated two independent ways rather
than by the route census alone: the census showed 19 expressions changing route, one of them outside
the new fixture, and a byte comparison of emitted GAS showed 1188 of 1190 artifacts identical with
exactly 2 differing — and the two accounts agree.

### Residual scope, filed separately

- **wasm answers `false` for equal constructor operands** because it compares scratch-block addresses
  rather than contents — **#511**. A different mechanism on a different backend; this fix does not
  reach it.

`in-progress` cleared. #511 has no worker and is selectable.
